/**
 * Single source of truth for GadgetLab catalog (TechVerse / Final Shop pattern).
 * Used by home, products, product detail, and cart pages.
 */
(function () {
  "use strict";

  window.GADGET_PRODUCTS = [
    {
      id: "p1",
      name: "Flight Noise Cancelling Headphones",
      category: "audio",
      price: 279,
      compareAt: 329,
      rating: 4.8,
      reviews: 1240,
      image:
        "https://imgs.search.brave.com/gaVWrEQ6W5WJpzedVJ8F0T5ieNakOgVxyY7BatbVTMU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHJhdmVsYW5kbGVp/c3VyZS5jb20vdGht/Yi80THlDYjctXzZl/TUJLVHQ5amljdG92/NkJsb1U9L2ZpdC1p/bi8xNTAweDI2Njgv/ZmlsdGVyczpub191/cHNjYWxlKCk6bWF4/X2J5dGVzKDE1MDAw/MCk6c3RyaXBfaWNj/KCkvdGFsLXNvdW5k/Y29yZS1zcGFjZS1v/bmUtcHJvLWZvbGRh/YmxlLW92ZXItZWFy/LWhlYWRwaG9uZXMt/YWZ0ZXItYWh1YW5n/LTYzMDgtMjMzYjVi/ODA0NTBiNGJjZDhl/MmNkMmU3MDUxOTQ1/YjguanBlZw",
      images: [
        "https://imgs.search.brave.com/gaVWrEQ6W5WJpzedVJ8F0T5ieNakOgVxyY7BatbVTMU/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/dHJhdmVsYW5kbGVp/c3VyZS5jb20vdGht/Yi80THlDYjctXzZl/TUJLVHQ5amljdG92/NkJsb1U9L2ZpdC1p/bi8xNTAweDI2Njgv/ZmlsdGVyczpub191/cHNjYWxlKCk6bWF4/X2J5dGVzKDE1MDAw/MCk6c3RyaXBfaWNj/KCkvdGFsLXNvdW5k/Y29yZS1zcGFjZS1v/bmUtcHJvLWZvbGRh/YmxlLW92ZXItZWFy/LWhlYWRwaG9uZXMt/YWZ0ZXItYWh1YW5n/LTYzMDgtMjMzYjVi/ODA0NTBiNGJjZDhl/MmNkMmU3MDUxOTQ1/YjguanBlZw",
        "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1523996798739-0ff655777930?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1575146106939-0318890123d1?auto=format&fit=crop&w=800&q=80"
      ],
      badge: "Best seller",
      featured: true,
      description:
        "Studio-grade active noise cancellation with 40-hour battery life, plush memory-foam ear cups, and multipoint Bluetooth for laptop and phone at once.",
      specs: [
        "Bluetooth 5.3 · Multipoint pairing",
        "ANC with transparency mode",
        "40h battery (30h with ANC on)",
        "USB-C fast charge — 10 min = 5h playback",
      ],
    },
    {
      id: "p2",
      name: "PulseWatch Ultra",
      category: "wearables",
      price: 399,
      compareAt: 449,
      rating: 4.9,
      reviews: 892,
      image:
        "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=800&q=80",
      badge: "New",
      featured: true,
      description:
        "AMOLED always-on display, ECG-ready sensors, 7-day battery, and 50m water resistance. Tracks sleep, stress, and workouts with on-device coaching.",
      specs: [
        "1.4\" AMOLED · Sapphire glass option",
        "GPS + heart rate + SpO₂",
        "7-day battery · 30h GPS mode",
        "Works with iOS & Android",
      ],
    },
    {
      id: "p3",
      name: "4K StreamCam Mini",
      category: "accessories",
      price: 149,
      compareAt: null,
      rating: 4.6,
      reviews: 356,
      image:
        "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80",
      badge: null,
      featured: false,
      description:
        "Pocket-sized 4K camera with gimbal stabilization, face tracking, and dual microphones—perfect for streaming and travel vlogs.",
      specs: [
        "4K30 / 1080p120",
        "3-axis stabilization",
        "USB-C & Wi-Fi transfer",
        "Includes travel case",
      ],
    },
    {
      id: "p4",
      name: "NeonBuds Wireless",
      category: "audio",
      price: 129,
      compareAt: 159,
      rating: 4.7,
      reviews: 2103,
      image:
        "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80",
      badge: "Deal",
      featured: true,
      description:
        "Low-latency gaming mode, IPX5 sweat resistance, and punchy bass tuning. Up to 8h per charge plus 24h from the case.",
      specs: [
        "Bluetooth 5.2 · Game mode under 60ms latency",
        "Touch controls · Voice assistant",
        "32h total with charging case",
        "Wireless charging case",
      ],
    },
    {
      id: "p5",
      name: "BoltSSD Portable 2TB",
      category: "computing",
      price: 189,
      compareAt: 219,
      rating: 4.8,
      reviews: 567,
      image:
        "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=800&q=80",
      badge: null,
      featured: false,
      description:
        "NVMe speeds up to 1050 MB/s in a shock-resistant enclosure. Hardware encryption and cross-platform support out of the box.",
      specs: [
        "2TB · USB 3.2 Gen 2",
        "1050 MB/s read / 1000 MB/s write",
        "IP55 · Drop resistant",
        "256-bit AES encryption",
      ],
    },
    {
      id: "p6",
      name: "TypeForge Mechanical Keyboard",
      category: "computing",
      price: 159,
      compareAt: null,
      rating: 4.5,
      reviews: 428,
      image:
        "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
      badge: null,
      featured: false,
      description:
        "Hot-swappable switches, gasket mount, and doubleshot PBT keycaps. Per-key RGB with software for macOS and Windows.",
      specs: [
        "75% layout · Gasket mount",
        "Hot-swap PCB",
        "PBT keycaps · South-facing RGB",
        "USB-C detachable cable",
      ],
    },
    {
      id: "p7",
      name: "Hiearcool USB C Hub for MacBook",
      category: "accessories",
      price: 59,
      compareAt: 79,
      rating: 4.4,
      reviews: 1834,
      image:
        "https://imgs.search.brave.com/GiPXwxAokZGW_spXvktuB-Di9Lc1L39bYOKcCdiniSo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzYxSGtSVEVjSEpM/LmpwZw",
      badge: "Deal",
      featured: false,
      description:
        "Hiearcool USB C Hub for MacBook – 7-in-1 USBC Adapter with 4K HDMI, 100W PD, USB 3.0 5Gbps Ports, SD/TF Card Reader – USB-C Dongle for Office, Meetings, Travel & Home Setup-Space Grey",
      specs: [
        "HDMI 2.0 · 4K60",
        "100W PD pass-through",
        "USB 3.2 Gen 1 ports",
        "Aluminum shell · Compact",
      ],
    },
    {
      id: "p8",
      name: "Smart Speaker",
      category: "smart-home",
      price: 99,
      compareAt: null,
      rating: 4.3,
      reviews: 672,
      image:
        "https://imgs.search.brave.com/uZgRRYOIk1iVmFVxR-0wsvDuKOwVSlf02tYLfYWw25U/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9zdDQu/ZGVwb3NpdHBob3Rv/cy5jb20vMTMxNjUz/NC8zOTA2NC9pLzQ1/MC9kZXBvc2l0cGhv/dG9zXzM5MDY0ODM0/MC1zdG9jay1waG90/by1zbWFydC1zcGVh/a2VyLWRldmljZS1s/aXZpbmctcm9vbS5q/cGc",
      badge: null,
      featured: false,
      description:
        "Room-filling 360° sound with adaptive EQ. Works with major voice assistants and pairs stereo with a second unit.",
      specs: [
        "360° driver array",
        "AirPlay 2 & Spotify Connect",
        "Adaptive room tuning",
        "Privacy mic mute",
      ],
    },
    {
      id: "p9",
      name: 'NovaTab 11" AMOLED',
      category: "computing",
      price: 449,
      compareAt: 499,
      rating: 4.7,
      reviews: 291,
      image:
        "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80",
      badge: "New",
      featured: true,
      description:
        "11\" 120Hz AMOLED, flagship chip, stylus support, and optional 5G. Thin, light, and built for split-screen productivity.",
      specs: [
        "11\" 120Hz AMOLED",
        "8GB RAM · 256GB storage",
        "Stylus compatible · Magnetic attach",
        "Quad speakers · Dolby Atmos",
      ],
    },
    {
      id: "p10",
      name: "SteadyShot Phone Gimbal",
      category: "accessories",
      price: 89,
      compareAt: null,
      rating: 4.6,
      reviews: 512,
      image:
        "https://imgs.search.brave.com/qd8vMyzJnppCm9Ji5G9K1frd5-477AKHvVKfqPmLkZc/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWFn/ZXMtbmEuc3NsLWlt/YWdlcy1hbWF6b24u/Y29tL2ltYWdlcy9J/LzcxbjhKNS12VnBM/LmpwZw",
      badge: null,
      featured: false,
      description:
        "Foldable 3-axis gimbal with active tracking, gesture control, and native app templates for TikTok and Reels.",
      specs: [
        "Payload up to 290g",
        "12h battery · USB-C",
        "Foldable travel design",
        "iOS & Android apps",
      ],
    },
    {
      id: "p11",
      name: "AeroBook Pro 14",
      category: "computing",
      price: 1299,
      compareAt: 1499,
      rating: 4.9,
      reviews: 450,
      image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80",
      badge: "New",
      featured: true,
      description: "Ultra-thin and light laptop with a stunning 14-inch display, powerful M3 chip, and all-day battery life. Perfect for professionals on the go.",
      specs: [
        "14-inch Liquid Retina XDR display",
        "Apple M3 Pro chip",
        "16GB unified memory",
        "512GB SSD storage",
      ],
    },
    {
      id: "p12",
      name: "Galaxy Buds Pro 2",
      category: "audio",
      price: 199,
      compareAt: 229,
      rating: 4.7,
      reviews: 1500,
      image: "https://imgs.search.brave.com/W8kLMmgZgCMBNXLUoshcN0RcBZNDUKG-V-UFzUejXU8/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bW9zLmNtcy5mdXR1/cmVjZG4ubmV0L3dk/alhrNEx4dDhuR1JB/Ym1xS3ludEsuanBl/Zw",
      badge: "Best seller",
      featured: false,
      description: "Immersive sound with intelligent Active Noise Cancellation. Ergonomic design for all-day comfort. Seamless connectivity with your Galaxy devices.",
      specs: [
        "24-bit Hi-Fi audio",
        "Intelligent ANC",
        "IPX7 water resistance",
        "Up to 29 hours of battery life",
      ],
    },
    {
      id: "p13",
      name: "Amazon Echo Show 8 (3rd gen)",
      category: "smart-home",
      price: 129,
      compareAt: null,
      rating: 4.5,
      reviews: 890,
      image: "https://imgs.search.brave.com/JF-5M-U4rHSmwUgh9dG5yRodlrITOFRWzu3GKKCmDaw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bW9zLmNtcy5mdXR1/cmVjZG4ubmV0L2hZ/M3ZvQ0Y0cDdwSjNa/SkQzenFLalouanBn",
      badge: null,
      featured: false,
      description: "The central brain of your smart home. Control lights, locks, thermostats, and more from a single app. Works with Alexa, Google Assistant, and Apple HomeKit.",
      specs: [
        "Zigbee, Z-Wave, and Wi-Fi compatible",
        "Voice control with major assistants",
        "Easy setup and automation",
        "Enhanced security features",
      ],
    },
    {
      id: "p14",
      name: "GoPro HERO12 Black",
      category: "accessories",
      price: 399,
      compareAt: 449,
      rating: 4.8,
      reviews: 780,
      image: "https://imgs.search.brave.com/7CCSZviMWhlTUDA5WgAbsopidrykzctBfuIFunjMM40/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bW9zLmNtcy5mdXR1/cmVjZG4ubmV0Lzkz/MzdaRmszak5QRXl5/eGtnN243dDMuanBn",
      badge: "New",
      featured: true,
      description: "The ultimate action camera. Stunning 5.3K video, HyperSmooth 6.0 stabilization, and a rugged, waterproof design. Capture your adventures like never before.",
      specs: [
        "5.3K60 + 4K120 video",
        "HyperSmooth 6.0 stabilization",
        "Waterproof to 33ft (10m)",
        "Front and rear LCD screens",
      ],
    },
    {
      id: "p15",
      name: "Fitbit Charge 6",
      category: "wearables",
      price: 159,
      compareAt: null,
      rating: 4.6,
      reviews: 1200,
      image: "https://imgs.search.brave.com/lq6tuhfSIfJKIc8l0a5dWWDpPL_4dd5GC65j1Oe_9e4/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tZWRp/YS5kY3JhaW5tYWtl/ci5jb20vaW1hZ2Vz/LzIwMjMvMTAvRml0/Yml0Q2hhcmdlNkV4/Y2VyY2lzZS5qcGc",
      badge: "Deal",
      featured: false,
      description: "Advanced fitness and health tracker with built-in GPS, heart rate monitoring, and sleep tracking. Stay motivated with daily readiness scores and active zone minutes.",
      specs: [
        "Built-in GPS",
        "24/7 heart rate tracking",
        "Sleep tracking and sleep score",
        "Up to 7 days of battery life",
      ],
    },
    {
      id: "p16",
      name: "Logitech MX Master 3S",
      category: "computing",
      price: 99,
      compareAt: null,
      rating: 4.9,
      reviews: 2500,
      image: "https://imgs.search.brave.com/ZnxxErtVqbQo6vhJDvoYBLGKE66hXY2L3RBNCLWbwEo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9jZG4u/bW9zLmNtcy5mdXR1/cmVjZG4ubmV0L3hV/VEhvaGZGUkVLMlNI/YkJDU2Y3bmIuanBn",
      badge: "Best seller",
      featured: true,
      description: "The ultimate mouse for power users. MagSpeed electromagnetic scrolling, 8K DPI sensor, and customizable buttons. Work seamlessly across multiple computers.",
      specs: [
        "MagSpeed scrolling",
        "8000 DPI sensor",
        "Flow cross-computer control",
        "USB-C quick charging",
      ],
    },
    {
        id: "p17",
        name: "APC Back-UPS Pro Gaming UPS",
        category: "computing",
        price: 189,
        compareAt: null,
        rating: 4.8,
        reviews: 3200,
        image: "https://imgs.search.brave.com/aZ9rTBNoFn2sRCDkYNgcqVKHd0z0yCPsVpBvjft5wKw/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9tLm1l/ZGlhLWFtYXpvbi5j/b20vaW1hZ2VzL1Mv/YXBsdXMtbWVkaWEv/dmMvNjIzZGE4MTct/ZGQwZi00YjQ4LTli/NGYtMTg2M2E4NWU5/NGVmLl9fQ1IwLDAs/MTAwMCw3NTBfUFQw/X1NYODAwX1YxX19f/LnBuZw",
        badge: null,
        featured: false,
        description: "Read anytime, anywhere with the best Kindle for reading. 32 GB of storage, wireless charging, and an auto-adjusting front light.",
        specs: [
          "6.8” display and thinner borders",
          "Adjustable warm light",
          "Wireless charging",
          "Waterproof (IPX8)",
        ],
      },
      {
        id: "p18",
        name: "Vanguard Alta Pro 2+ 263AB100",
        category: "accessories",
        price: 49,
        compareAt: 59,
        rating: 4.7,
        reviews: 1800,
        image: "https://imgs.search.brave.com/MOByGwssZSwT0p1kafrE2lz5QIR8zkQdc2TyFPKibKA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/b3B0aWNzLXByby5j/b20vUHJvZHVrdGJp/bGRlci96b29tLzU1/ODY0XzYvVmFuZ3Vh/cmQtQWx1bWluaXVt/LXRyaXBvZC1BbHRh/LVByby0yLTI2M0FC/MTAwLmpwZw",
        badge: "Deal",
        featured: false,
        description: "The freedom of wireless charging on the go. This 10,000mAh portable charger supports Qi wireless charging and high-speed USB-C charging.",
        specs: [
          "10,000mAh capacity",
          "Qi-certified wireless charging",
          "18W USB-C Power Delivery",
          "MultiProtect safety system",
        ],
      },
      {
        id: "p19",
        name: "Bose SoundLink Revolve+",
        category: "audio",
        price: 329,
        compareAt: null,
        rating: 4.7,
        reviews: 1100,
        image: "https://imgs.search.brave.com/R3vXo5FjuKzE1Yg-y-RVq2hQZOxxtEroSdaVviFAsTY/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly93d3cu/Y25ldC5jb20vYS9p/bWcvcmVzaXplLzcz/NDU5YTcyMWJjZTEz/ZDllYWExMjRkYTZk/NTZkN2NkZjk0YjFl/ZmMvaHViLzIwMTcv/MDQvMTkvOWM2NWQ5/YzYtYTU0ZS00NTNj/LTg2NTgtYjMxN2Rl/NTVlZDNkL2Jvc2Ut/c291bmRsaW5rLXJl/dm9sdmUtMDkuanBn/P2F1dG89d2VicCZ3/aWR0aD0xMjAw",
        badge: null,
        featured: false,
        description: "The best-performing portable Bluetooth speaker from Bose, engineered to spread deep, jaw-dropping sound in every direction.",
        specs: [
          "360° sound",
          "Up to 17 hours of battery life",
          "Water- and dust-resistant (IP55)",
          "Built-in microphone for calls",
        ],
      },
      {
        id: "p20",
        name: "Ring Video Doorbell Pro 2",
        category: "smart-home",
        price: 249,
        compareAt: null,
        rating: 4.6,
        reviews: 950,
        image: "https://imgs.search.brave.com/2nB6qgZI8uN3NATy-gF8O0cEWZYCyLz9M2L1cja2pGA/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9lbi11/ay5yaW5nLmNvbS9j/ZG4vc2hvcC9maWxl/cy9yaW5nX2JhdHRl/cnktdmlkZW8tZG9v/cmJlbGwtcHJvX3Nu/XzAyX2ZlYXR1cmVz/X2VuXzE1MDB4MTUw/MF8zMDZhMDkwNy1j/YmQwLTRkMzEtYWRm/ZC0wYjg5MzQ1YzMw/NGRfMTI4MHgxMjgw/X2Nyb3BfY2VudGVy/LmpwZz92PTE3NTY0/NDg5MzQ",
        badge: "New",
        featured: true,
        description: "Premium video doorbell with 3D Motion Detection, Head-to-Toe HD+ Video, and built-in Alexa Greetings. See and speak to visitors from anywhere.",
        specs: [
          "1536p HD+ Video",
          "3D Motion Detection",
          "Two-Way Talk with Audio+",
          "Wired installation",
        ],
      }
  ];

  window.GADGET_CATEGORY_LABEL = {
    audio: "Audio",
    wearables: "Wearables",
    computing: "Computing",
    accessories: "Accessories",
    "smart-home": "Smart home",
  };
})();